### ISSUE TITLE
Vertex AI Agent API document pointing to internal website

### ISSUE THREAD

**Issue by nwipfli** [GoogleCloudPlatform/applied-ai-engineering-samples#105]
In this [notebook](https://github.com/GoogleCloudPlatform/applied-ai-engineering-samples/blob/agents-api-notebooks/genai-on-vertex-ai/vertex_ai_agent_api/notebooks/getting_started_vertex_agent_api.ipynb) and the following line:

This notebook shows how to use the [Vertex AI Agent API](https://cloud.google.com/vertex-ai/generative-ai/docs/agent-api/overview).

the documentation points to a Google internal website. The notebook is public but the documentation is not publicly accessible.

**Comment by Abhishekbhagwat** [comment]
@anifort fyi

**Comment by anifort** [comment]
This notebook is not on the main brunch of thus repository and currently WIP

**Comment by anifort** [comment]
Brunch WIP
