### ISSUE TITLE
RAG Playground's setup documentation is missing Cloud Build SA roles 

### ISSUE THREAD

**Issue by phriscage** [GoogleCloudPlatform/applied-ai-engineering-samples#113]
# Issue/Request:
The [RAG Playground](https://github.com/GoogleCloudPlatform/applied-ai-engineering-samples/tree/rag-playground) branch's README.md setup instructions [here](https://github.com/GoogleCloudPlatform/applied-ai-engineering-samples/blob/rag-playground/README.md#-getting-started-) are missing the following IAM roles that need to be granted to the Cloud Build Service Account. These roles are required for the SA when executing the Terraform recipes on a new GCP project:

`roles/logging.LogWriter`
`roles/iam.securityAdmin`
`roles/cloudfunctions.developer`
`roles/firebase.admin` 
        
# Suggestion/Fix:
Update the documentation to include missing IAM roles

**Comment by RajeshThallam** [comment]
Fixed with #114
