### ISSUE TITLE
"bank_of_anthos_codebase.zip" is correct codebase?

### ISSUE THREAD

**Issue by imcboofel** [GoogleCloudPlatform/applied-ai-engineering-samples#34]
Hi there,

Recently I ran a notebook named "5_codey_talk_to_codebase_example.ipynb" from your repository.
However, if I load the codebase into gcs and run the cell that process the codebase as per the guide,
and when the process reads the csv function, it encountered an error with "ParserError".

I try to find the root cause to this issue, I finally know that was occurred by "bank_of_anthos_codebase.zip" containing the "Pokemon data",
Is it suitable for the embedding process? I think that is not identical to the original processed output message in your default notebook.

Thank you

**Comment by genaimagician** [comment]
Hi @imcboofel, can you use the bank-of-anthos.zip in the utilities folder? I just checked in that zip file. That's the same zip file I used for testing. Please let me know if you see any issues.

**Comment by RajeshThallam** [comment]
Closing as issue is fixed. Please reopen if needed.

**Comment by djmartberry66** [comment]
Nice

**Comment by djmartberry66** [comment]
> Hi there,
> 
> Recently I ran a notebook named "5_codey_talk_to_codebase_example.ipynb" from your repository. However, if I load the codebase into gcs and run the cell that process the codebase as per the guide, and when the process reads the csv function, it encountered an error with "ParserError".
> 
> I try to find the root cause to this issue, I finally know that was occurred by "bank_of_anthos_codebase.zip" containing the "Pokemon data", Is it suitable for the embedding process? I think that is not identical to the original processed output message in your default notebook.
> 
> Thank you
